/**************************
***** Compiler Parameters *****
***************************
@P EffectName: MeshOutlineShader
***************************
****  ConstantBuffers  ****
***************************
cbuffer PerDraw [Size: 416]
@C    World_id21 => Transformation.World
@C    WorldInverse_id22 => Transformation.WorldInverse
@C    WorldInverseTranspose_id23 => Transformation.WorldInverseTranspose
@C    WorldView_id24 => Transformation.WorldView
@C    WorldViewInverse_id25 => Transformation.WorldViewInverse
@C    WorldViewProjection_id26 => Transformation.WorldViewProjection
@C    WorldScale_id27 => Transformation.WorldScale
@C    EyeMS_id28 => Transformation.EyeMS
cbuffer Globals [Size: 112]
@C    Texture0TexelSize_id30 => Texturing.Texture0TexelSize
@C    Texture1TexelSize_id32 => Texturing.Texture1TexelSize
@C    Texture2TexelSize_id34 => Texturing.Texture2TexelSize
@C    Texture3TexelSize_id36 => Texturing.Texture3TexelSize
@C    Texture4TexelSize_id38 => Texturing.Texture4TexelSize
@C    Texture5TexelSize_id40 => Texturing.Texture5TexelSize
@C    Texture6TexelSize_id42 => Texturing.Texture6TexelSize
@C    Texture7TexelSize_id44 => Texturing.Texture7TexelSize
@C    Texture8TexelSize_id46 => Texturing.Texture8TexelSize
@C    Texture9TexelSize_id48 => Texturing.Texture9TexelSize
@C    Color_id91 => MeshOutlineShader.Color
@C    Intensity_id92 => MeshOutlineShader.Intensity
@C    Size_id93 => MeshOutlineShader.Size
***************************
******  Resources    ******
***************************
@R    PerDraw => PerDraw [Stage: Vertex, Slot: (0-0)]
@R    Globals => Globals [Stage: Vertex, Slot: (1-1)]
@R    Globals => Globals [Stage: Pixel, Slot: (0-0)]
***************************
*****     Sources     *****
***************************
@S    MeshOutlineShader => 4949a4a9739d70e3d1d2e25a8c2e9fb3
@S    ShaderBase => 4ecbcd2528b64a79eebe81a863892d8c
@S    ShaderBaseStream => b705b699a7385d39c7de52a8d13f3978
@S    Transformation => 7c995c14d4da978d7dca233f15f1e7c0
@S    Texturing => 91ef3011c1071c2e5d41cd3ee0418b18
@S    PositionStream4 => 992b49e1b4dd13d8ef84a05830d70229
***************************
*****     Stages      *****
***************************
@G    Vertex => af1ff0e184cdfd984a7be88f321c9ab6
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDraw
// {
//
//   float4x4 World_id21;               // Offset:    0 Size:    64 [unused]
//   float4x4 WorldInverse_id22;        // Offset:   64 Size:    64 [unused]
//   float4x4 WorldInverseTranspose_id23;// Offset:  128 Size:    64 [unused]
//   float4x4 WorldView_id24;           // Offset:  192 Size:    64 [unused]
//   float4x4 WorldViewInverse_id25;    // Offset:  256 Size:    64 [unused]
//   float4x4 WorldViewProjection_id26; // Offset:  320 Size:    64
//   float3 WorldScale_id27;            // Offset:  384 Size:    12
//   float4 EyeMS_id28;                 // Offset:  400 Size:    16 [unused]
//
// }
//
// cbuffer Globals
// {
//
//   float2 Texture0TexelSize_id30;     // Offset:    0 Size:     8 [unused]
//   float2 Texture1TexelSize_id32;     // Offset:    8 Size:     8 [unused]
//   float2 Texture2TexelSize_id34;     // Offset:   16 Size:     8 [unused]
//   float2 Texture3TexelSize_id36;     // Offset:   24 Size:     8 [unused]
//   float2 Texture4TexelSize_id38;     // Offset:   32 Size:     8 [unused]
//   float2 Texture5TexelSize_id40;     // Offset:   40 Size:     8 [unused]
//   float2 Texture6TexelSize_id42;     // Offset:   48 Size:     8 [unused]
//   float2 Texture7TexelSize_id44;     // Offset:   56 Size:     8 [unused]
//   float2 Texture8TexelSize_id46;     // Offset:   64 Size:     8 [unused]
//   float2 Texture9TexelSize_id48;     // Offset:   72 Size:     8 [unused]
//   float4 Color_id91;                 // Offset:   80 Size:    16 [unused]
//   float Intensity_id92;              // Offset:   96 Size:     4 [unused]
//   float Size_id93;                   // Offset:  100 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// PerDraw                           cbuffer      NA          NA            cb0      1 
// Globals                           cbuffer      NA          NA            cb1      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// NORMAL                   0   xyz         1     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[25], immediateIndexed
dcl_constantbuffer CB1[7], immediateIndexed
dcl_input v0.xyzw
dcl_input v1.xyz
dcl_output_siv o0.xyzw, position
dcl_temps 1
//
// Initial variable locations:
//   v0.x <- __input__.Position_id87.x; v0.y <- __input__.Position_id87.y; v0.z <- __input__.Position_id87.z; v0.w <- __input__.Position_id87.w; 
//   v1.x <- __input__.Normal_id90.x; v1.y <- __input__.Normal_id90.y; v1.z <- __input__.Normal_id90.z; 
//   o0.x <- <VSMain return value>.ShadingPosition_id0.x; o0.y <- <VSMain return value>.ShadingPosition_id0.y; o0.z <- <VSMain return value>.ShadingPosition_id0.z; o0.w <- <VSMain return value>.ShadingPosition_id0.w
//
#line 146 "C:\Users\ravaz\Documents\Trabajo\Alpine Sloths\VVVV PLAY\Games\VL.Breakout\log\shader_MeshOutlineShader_32388b809134d4813bf02aecbb908780.hlsl"
mad r0.x, -cb1[6].y, l(0.100000), l(1.000000)
max r0.x, r0.x, l(0.900000)
min r0.x, r0.x, l(1.000000)
add r0.xyz, -r0.xxxx, cb0[24].xyzx
mul r0.xyz, r0.xyzx, v1.xyzx  // r0.x <- scaling.x; r0.y <- scaling.y; r0.z <- scaling.z

#line 147
mov r0.w, l(0)
add r0.xyzw, r0.xyzw, v0.xyzw
dp4 o0.x, r0.xyzw, cb0[20].xyzw
dp4 o0.y, r0.xyzw, cb0[21].xyzw
dp4 o0.z, r0.xyzw, cb0[22].xyzw
dp4 o0.w, r0.xyzw, cb0[23].xyzw

#line 165
ret 
// Approximately 12 instruction slots used
@G    Pixel => 53408519fee991155d2d81370f4552f8
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer Globals
// {
//
//   float2 Texture0TexelSize_id30;     // Offset:    0 Size:     8 [unused]
//   float2 Texture1TexelSize_id32;     // Offset:    8 Size:     8 [unused]
//   float2 Texture2TexelSize_id34;     // Offset:   16 Size:     8 [unused]
//   float2 Texture3TexelSize_id36;     // Offset:   24 Size:     8 [unused]
//   float2 Texture4TexelSize_id38;     // Offset:   32 Size:     8 [unused]
//   float2 Texture5TexelSize_id40;     // Offset:   40 Size:     8 [unused]
//   float2 Texture6TexelSize_id42;     // Offset:   48 Size:     8 [unused]
//   float2 Texture7TexelSize_id44;     // Offset:   56 Size:     8 [unused]
//   float2 Texture8TexelSize_id46;     // Offset:   64 Size:     8 [unused]
//   float2 Texture9TexelSize_id48;     // Offset:   72 Size:     8 [unused]
//   float4 Color_id91;                 // Offset:   80 Size:    16
//   float Intensity_id92;              // Offset:   96 Size:     4
//   float Size_id93;                   // Offset:  100 Size:     4 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// Globals                           cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[7], immediateIndexed
dcl_output o0.xyzw
//
// Initial variable locations:
//   v0.x <- __input__.ShadingPosition_id0.x; v0.y <- __input__.ShadingPosition_id0.y; v0.z <- __input__.ShadingPosition_id0.z; v0.w <- __input__.ShadingPosition_id0.w; 
//   o0.x <- <PSMain return value>.ColorTarget_id2.x; o0.y <- <PSMain return value>.ColorTarget_id2.y; o0.z <- <PSMain return value>.ColorTarget_id2.z; o0.w <- <PSMain return value>.ColorTarget_id2.w
//
#line 152 "C:\Users\ravaz\Documents\Trabajo\Alpine Sloths\VVVV PLAY\Games\VL.Breakout\log\shader_MeshOutlineShader_32388b809134d4813bf02aecbb908780.hlsl"
mul o0.xyzw, cb0[5].xyzw, cb0[6].xxxx

#line 155
ret 
// Approximately 2 instruction slots used
***************************
*************************/
struct PS_STREAMS 
{
    float4 ColorTarget_id2;
};
struct PS_OUTPUT 
{
    float4 ColorTarget_id2 : SV_Target0;
};
struct PS_INPUT 
{
    float4 ShadingPosition_id0 : SV_Position;
};
struct VS_STREAMS 
{
    float4 Position_id87;
    float3 Normal_id90;
    float4 ShadingPosition_id0;
};
struct VS_OUTPUT 
{
    float4 ShadingPosition_id0 : SV_Position;
};
struct VS_INPUT 
{
    float4 Position_id87 : POSITION;
    float3 Normal_id90 : NORMAL;
};
cbuffer PerDraw 
{
    float4x4 World_id21;
    float4x4 WorldInverse_id22;
    float4x4 WorldInverseTranspose_id23;
    float4x4 WorldView_id24;
    float4x4 WorldViewInverse_id25;
    float4x4 WorldViewProjection_id26;
    float3 WorldScale_id27;
    float4 EyeMS_id28;
};
cbuffer PerView 
{
    float4x4 View_id14;
    float4x4 ViewInverse_id15;
    float4x4 Projection_id16;
    float4x4 ProjectionInverse_id17;
    float4x4 ViewProjection_id18;
    float2 ProjScreenRay_id19;
    float4 Eye_id20;
    float4 Viewport_id94;
};
cbuffer Globals 
{
    float2 Texture0TexelSize_id30;
    float2 Texture1TexelSize_id32;
    float2 Texture2TexelSize_id34;
    float2 Texture3TexelSize_id36;
    float2 Texture4TexelSize_id38;
    float2 Texture5TexelSize_id40;
    float2 Texture6TexelSize_id42;
    float2 Texture7TexelSize_id44;
    float2 Texture8TexelSize_id46;
    float2 Texture9TexelSize_id48;
    float4 Color_id91;
    float Intensity_id92;
    float Size_id93;
};
Texture2D Texture0_id29;
Texture2D Texture1_id31;
Texture2D Texture2_id33;
Texture2D Texture3_id35;
Texture2D Texture4_id37;
Texture2D Texture5_id39;
Texture2D Texture6_id41;
Texture2D Texture7_id43;
Texture2D Texture8_id45;
Texture2D Texture9_id47;
TextureCube TextureCube0_id49;
TextureCube TextureCube1_id50;
TextureCube TextureCube2_id51;
TextureCube TextureCube3_id52;
Texture3D Texture3D0_id53;
Texture3D Texture3D1_id54;
Texture3D Texture3D2_id55;
Texture3D Texture3D3_id56;
SamplerState Sampler_id57;
SamplerState PointSampler_id58 
{
    Filter = MIN_MAG_MIP_POINT;
};
SamplerState LinearSampler_id59 
{
    Filter = MIN_MAG_MIP_LINEAR;
};
SamplerState LinearBorderSampler_id60 
{
    Filter = MIN_MAG_MIP_LINEAR;
    AddressU = Border;
    AddressV = Border;
};
SamplerComparisonState LinearClampCompareLessEqualSampler_id61 
{
    Filter = COMPARISON_MIN_MAG_LINEAR_MIP_POINT;
    AddressU = Clamp;
    AddressV = Clamp;
    ComparisonFunc = LessEqual;
};
SamplerState AnisotropicSampler_id62 
{
    Filter = ANISOTROPIC;
};
SamplerState AnisotropicRepeatSampler_id63 
{
    Filter = ANISOTROPIC;
    AddressU = Wrap;
    AddressV = Wrap;
    MaxAnisotropy = 16;
};
SamplerState PointRepeatSampler_id64 
{
    Filter = MIN_MAG_MIP_POINT;
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState LinearRepeatSampler_id65 
{
    Filter = MIN_MAG_MIP_LINEAR;
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState RepeatSampler_id66 
{
    AddressU = Wrap;
    AddressV = Wrap;
};
SamplerState Sampler0_id67;
SamplerState Sampler1_id68;
SamplerState Sampler2_id69;
SamplerState Sampler3_id70;
SamplerState Sampler4_id71;
SamplerState Sampler5_id72;
SamplerState Sampler6_id73;
SamplerState Sampler7_id74;
SamplerState Sampler8_id75;
SamplerState Sampler9_id76;
float4 projToWorld_id2(in float4 pos, in float3 normal)
{
    float3 scaling = normal * (WorldScale_id27 - clamp(1 - (Size_id93 * 0.1), 0.9, 1.0));
    return mul(pos + float4(scaling.x, scaling.y, scaling.z, 0), WorldViewProjection_id26);
}
PS_OUTPUT PSMain(PS_INPUT __input__)
{
    PS_STREAMS streams = (PS_STREAMS)0;
    streams.ColorTarget_id2 = Color_id91 * Intensity_id92;
    PS_OUTPUT __output__ = (PS_OUTPUT)0;
    __output__.ColorTarget_id2 = streams.ColorTarget_id2;
    return __output__;
}
VS_OUTPUT VSMain(VS_INPUT __input__)
{
    VS_STREAMS streams = (VS_STREAMS)0;
    streams.Position_id87 = __input__.Position_id87;
    streams.Normal_id90 = __input__.Normal_id90;
    streams.ShadingPosition_id0 = projToWorld_id2(streams.Position_id87, streams.Normal_id90);
    VS_OUTPUT __output__ = (VS_OUTPUT)0;
    __output__.ShadingPosition_id0 = streams.ShadingPosition_id0;
    return __output__;
}
